# Projeto 1

Modelo de entrega da questão 2.

Respeite as divisões em Markdown para facilitar a navegação no relatório.

## Questão 2: Resolvendo sistemas tridiagonais.

### Questão 2.1
Escreva, em Python ou Julia, uma função `solve_tridiag(A, b)` que recebe uma matriz quadrada $A$ e um vetor $b$ e retorna a solução do sistema $Ax = b$ (você pode supor que $A$ é inversível).

In [158]:
import numpy as np
import timeit

#### Explicação
Professor, minha ideia inicial era calcular a matriz inversa e depois apenas resolver o sistema linear multiplicando $x = A^{-1}b$ depois de assistir duas aulas do MIT OpenCourseWare aprendi que calcular a 

In [159]:
def solve_tridiag(A, b):
    A_nrow, A_ncol = A.shape
    
    L = np.identity(A_nrow)
    
    for i in range(A_nrow-1):
        t = A[i+1,i]/A[i,i]
        A[i+1] = A[i+1] - t*A[i]
        L[i+1,i] = t
        
    y = np.zeros(A_nrow)
    y[0] = b[0]
    for i in range(1, A_nrow):
        y[i] = b[i] - L[i,i-1]*y[i-1]
    
    x = np.zeros(A_nrow)
    x[A_nrow-1] =  y[A_nrow-1]/A[A_nrow-1,A_nrow-1]
    for i in reversed(range(A_nrow-1)):
        x[i] = (y[i] - x[i+1]*A[i, i+1])/A[i,i]
        
    return x

### Questão 2.2
Verifique que sua função está correta, fazendo alguns testes.

In [160]:
A1 = np.array([
        [ 2.0, -1.0,  0.0],
        [-1.0,  2.0, -1.0],
        [ 0.0, -1.0,  2.0]
    ])
b1 = np.array([1.0, 0.0, 1.0])


print(solve_tridiag(A1.copy(),b1.copy()))
print(np.linalg.solve(A1.copy(), b1.copy()))



[1. 1. 1.]
[1. 1. 1.]


In [161]:
n2 = 5
A2 = np.diag(np.full(n2, 2.0)) + \
    np.diag(np.full(n2-1, -1.0), -1) + \
    np.diag(np.full(n2-1, -1.0), 1)
b2 = np.array([10.0, 20.0, 30.0, 40.0, 50.0])

print(solve_tridiag(A2.copy(),b2.copy()))
print(np.linalg.solve(A2.copy(), b2.copy()))

[ 58.33333333 106.66666667 135.         133.33333333  91.66666667]
[ 58.33333333 106.66666667 135.         133.33333333  91.66666667]


In [162]:
A3 = np.array([
        [10.0,  1.0,  0.0,  0.0],
        [ 2.0, 12.0,  3.0,  0.0],
        [ 0.0,  4.0, 15.0,  5.0],
        [ 0.0,  0.0,  6.0, 20.0]
    ])
b3 = np.array([5.0, -2.0, 8.0, 1.0])

print(solve_tridiag(A3.copy(),b3.copy()))
print(np.linalg.solve(A3.copy(), b3.copy()))

[ 0.54327902 -0.43279022  0.70230821 -0.16069246]
[ 0.54327902 -0.43279022  0.70230821 -0.16069246]


### Questão 2.3
Qual é a complexidade computacional da sua função?

### Questão 2.4
A partir de que tamanho de matriz $A$ a função `solve_tridiag` se torna mais rápida do que a função `numpy.linalg.solve` (ou `\`, em Julia)?
Como você fez para chegar neste resultado?

In [163]:
N = 20000 # Tamanho
A_rand = np.diag(np.random.rand(N)) + np.diag(np.random.rand(N-1), -1) + np.diag(np.random.rand(N-1), 1)
b_rand = np.random.rand(N)
x_rand_esp = np.linalg.solve(A_rand, b_rand)

In [ ]:
tempo = timeit.timeit("solve_tridiag(A_rand.copy(),b_rand.copy())", globals= globals(), number = 1)
print(tempo)
tempo = timeit.timeit("np.linalg.solve(A_rand.copy(),b_rand.copy())", globals= globals(), number = 1)
print(tempo)

8.097733000002336


In [ ]:
# Código auxiliar para a questão 2.4
tempo = timeit.timeit("solve_tridiag(A3.copy(),b3.copy())", globals= globals(), number = 100)
print(tempo)
tempo = timeit.timeit("np.linalg.solve(A3.copy(), b3.copy())", globals= globals(), number = 100)
print(tempo)

0.002967500011436641
0.0012821999989682809


(Resposta em texto)